os:
- Visual Studio 2015
- Visual Studio 2017

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - C:\projects\function-ref\build\Debug\tests.exe

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
